server:
    port: 9997
 
spring:
  application:
      name: api-configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jonavcar/Proyecto3_ConfigData
          searchPaths: application-config
          default-label: main
          username: jonavcar@gmail.com
          password: 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
